In [1]:
import pandas as pd

In [3]:
excel_file = pd.ExcelFile("online_retail_II.xlsx")

print(excel_file.sheet_names)

df = pd.read_excel("online_retail_II.xlsx", sheet_name=excel_file.sheet_names[0])

['Year 2009-2010', 'Year 2010-2011']

In [4]:
print("Shape before removing duplicates:", df.shape)

Shape before removing duplicates: (525461, 8)

In [7]:
duplicate_count = df.duplicated().sum()

print("Duplicate Rows:", duplicate_count)

Duplicate Rows: 6865

In [9]:
df[df.duplicated()].head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
371,489517,21912,VINTAGE SNAKES & LADDERS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
383,489517,22130,PARTY CONE CHRISTMAS DECORATION,6,2009-12-01 11:34:00,0.85,16329.0,United Kingdom
384,489517,22319,HAIRCLIPS FORTIES FABRIC ASSORTED,12,2009-12-01 11:34:00,0.65,16329.0,United Kingdom
385,489517,21913,VINTAGE SEASIDE JIGSAW PUZZLES,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom
386,489517,21821,GLITTER STAR GARLAND WITH BELLS,1,2009-12-01 11:34:00,3.75,16329.0,United Kingdom

In [11]:
df = df.drop_duplicates()

In [13]:
print("Duplicate Rows After Cleaning:", df.duplicated().sum())

Duplicate Rows After Cleaning: 0

In [15]:
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (518596, 8)

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 518596 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      518596 non-null  object
 1   StockCode    518596 non-null  object
 2   Description  515668 non-null  object
 3   Quantity     518596 non-null  int64
 4   InvoiceDate  518596 non-null  datetime64[ns]
 5   Price        518596 non-null  float64
 6   Customer ID  410763 non-null  float64
 7   Country      518596 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 35.6+ MB

In [19]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      2928
Quantity            0
InvoiceDate         0
Price               0
Customer ID    107833
Country             0
dtype: int64

In [21]:
df.describe()

,Quantity,InvoiceDate,Price,Customer ID
count,518596.000000,518596,518596.000000,410763.000000
mean,10.438152,2010-06-28 06:43:01.573016320,4.716176,15353.621857
min,-9600.000000,2009-12-01 07:45:00,-53594.360000,12346.000000
25%,1.000000,2010-03-21 11:07:00,1.250000,13979.000000
50%,3.000000,2010-07-05 15:42:00,2.100000,15311.000000
75%,10.000000,2010-10-15 11:40:00,4.210000,16797.000000
max,19152.000000,2010-12-09 20:01:00,25111.090000,18287.000000
std,108.126593,NaN,147.090460,1681.657665

In [23]:
df.describe(include="object")

        Invoice StockCode                         Description         Country
count    518596    518596                              515668          518596
unique    28816      4632                                4681              40
top      537434    85123A  WHITE HANGING HEART T-LIGHT HOLDER  United Kingdom
freq        675      3470                                3503          479047

In [25]:
df[df["Quantity"] < 0]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
178,C489449,22087,PAPER BUNTING WHITE LACE,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
179,C489449,85206A,CREAM FELT EASTER EGG BASKET,-6,2009-12-01 10:33:00,1.65,16321.0,Australia
180,C489449,21895,POTTING SHED SOW 'N' GROW SET,-4,2009-12-01 10:33:00,4.25,16321.0,Australia
181,C489449,21896,POTTING SHED TWINE,-6,2009-12-01 10:33:00,2.10,16321.0,Australia
182,C489449,22083,PAPER CHAIN KIT RETRO SPOT,-12,2009-12-01 10:33:00,2.95,16321.0,Australia
...,...,...,...,...,...,...,...,...
525231,538159,21324,NaN,-18,2010-12-09 17:17:00,0.00,NaN,United Kingdom
525232,538158,20892,NaN,-32,2010-12-09 17:17:00,0.00,NaN,United Kingdom
525234,538161,46000S,Dotcom sales,-100,2010-12-09 17:25:00,0.00,NaN,United Kingdom
525235,538162,46000M,Dotcom sales,-100,2010-12-09 17:25:00,0.00,NaN,United Kingdom
525282,C538164,35004B,SET OF 3 BLACK FLYING DUCKS,-1,2010-12-09 17:32:00,1.95,14031.0,United Kingdom

In [27]:
df["Invoice"].isnull().sum()

0

In [29]:
df["Customer ID"].isnull().sum()

107833

In [31]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

print(df["InvoiceDate"].dtype)

datetime64[ns]

In [33]:
df.to_csv("cleaned_online_retail.csv", index=False)