In [1]:
import pandas as pd

In [17]:
import pandas as pd

df = pd.read_csv("cleaned_online_retail.csv")

In [19]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [21]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [23]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [25]:
df["FirstPurchaseDate"] = (
    df.groupby("Customer ID")["InvoiceDate"]
      .transform("min")
)

In [27]:
df[["Customer ID", "InvoiceDate", "FirstPurchaseDate"]].head(10)

   Customer ID         InvoiceDate   FirstPurchaseDate
0      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
1      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
2      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
3      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
4      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
5      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
6      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
7      13085.0 2009-12-01 07:45:00 2009-12-01 07:45:00
8      13085.0 2009-12-01 07:46:00 2009-12-01 07:45:00
9      13085.0 2009-12-01 07:46:00 2009-12-01 07:45:00

In [29]:
df["FirstPurchaseDate"].isnull().sum()

107833

In [31]:
df["Customer ID"].isnull().sum()

107833

In [33]:
df[df["Customer ID"].isnull()][["Customer ID", "InvoiceDate", "FirstPurchaseDate"]].head()

     Customer ID         InvoiceDate FirstPurchaseDate
263          NaN 2009-12-01 10:52:00               NaT
283          NaN 2009-12-01 10:52:00               NaT
284          NaN 2009-12-01 10:53:00               NaT
462          NaN 2009-12-01 11:44:00               NaT
569          NaN 2009-12-01 11:49:00               NaT

In [35]:
df = df.dropna(subset=["Customer ID"])

In [37]:
df["FirstPurchaseDate"] = (
    df.groupby("Customer ID")["InvoiceDate"]
      .transform("min")
)

In [39]:
df["FirstPurchaseDate"].isnull().sum()

0