In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("cohort_index_dataset.csv")

In [5]:
df[["Customer ID", "Invoice"]].head()

   Customer ID Invoice
0      13085.0  489434
1      13085.0  489434
2      13085.0  489434
3      13085.0  489434
4      13085.0  489434

In [7]:
customer_orders = (
    df.groupby("Customer ID")["Invoice"]
      .nunique()
      .reset_index()
)

In [9]:
customer_orders.columns = ["Customer ID", "Total_Purchases"]

In [11]:
customer_orders.head()

   Customer ID  Total_Purchases
0      12346.0               17
1      12347.0                7
2      12348.0                5
3      12349.0                5
4      12350.0                1

In [13]:
purchase_frequency = customer_orders["Total_Purchases"].mean()

In [15]:
print("Purchase Frequency:", round(purchase_frequency, 2))

Purchase Frequency: 7.47