In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("cohort_index_dataset.csv")

In [5]:
df[["Customer ID", "InvoiceDate"]].head()

   Customer ID          InvoiceDate
0      13085.0  2009-12-01 07:45:00
1      13085.0  2009-12-01 07:45:00
2      13085.0  2009-12-01 07:45:00
3      13085.0  2009-12-01 07:45:00
4      13085.0  2009-12-01 07:45:00

In [7]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [9]:
customer_lifespan = (
    df.groupby("Customer ID")["InvoiceDate"]
      .agg(["min", "max"])
      .reset_index()
)

In [11]:
customer_lifespan.columns = [
    "Customer ID",
    "First_Purchase",
    "Last_Purchase"
]

In [13]:
customer_lifespan["Lifespan_Days"] = (
    customer_lifespan["Last_Purchase"]
    - customer_lifespan["First_Purchase"]
).dt.days

In [15]:
customer_lifespan["Lifespan_Months"] = (
    customer_lifespan["Lifespan_Days"] / 30
).round(2)

In [17]:
customer_lifespan.head()

,Customer ID,First_Purchase,Last_Purchase,Lifespan_Days,Lifespan_Months
0,12346.0,2009-12-14 08:34:00,2011-01-18 10:17:00,400,13.33
1,12347.0,2010-10-31 14:20:00,2011-10-31 12:25:00,364,12.13
2,12348.0,2010-09-27 14:59:00,2011-09-25 13:13:00,362,12.07
3,12349.0,2009-12-04 12:49:00,2011-11-21 09:51:00,716,23.87
4,12350.0,2011-02-02 16:01:00,2011-02-02 16:01:00,0,0.00

In [19]:
average_lifespan = customer_lifespan["Lifespan_Months"].mean()

print("Average Customer Lifespan:", round(average_lifespan, 2), "months")

Average Customer Lifespan: 9.07 months

In [21]:
customer_lifespan.to_csv("customer_lifespan.csv", index=False)