In [1]:
from google.colab import files

uploaded = files.upload()

Saving cohort_index_dataset.csv to cohort_index_dataset.csv

In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("cohort_index_dataset.csv")

In [3]:
total_revenue = df["Revenue"].sum()

total_orders = df["Invoice"].nunique()

total_customers = df["Customer ID"].nunique()

aov = total_revenue / total_orders

purchase_frequency = total_orders / total_customers

customer_lifespan = 12

cltv = aov * purchase_frequency * customer_lifespan

In [4]:
print("Total Revenue:", round(total_revenue, 2))
print("Total Orders:", total_orders)
print("Total Customers:", total_customers)
print("Average Order Value:", round(aov, 2))
print("Purchase Frequency:", round(purchase_frequency, 2))
print("Customer Lifetime Value:", round(cltv, 2))

Total Revenue: 18972492.19
Total Orders: 52961
Total Customers: 5924
Average Order Value: 358.24
Purchase Frequency: 8.94
Customer Lifetime Value: 38431.79

In [5]:
metrics_summary = pd.DataFrame({
    "Metric": [
        "Total Revenue",
        "Total Orders",
        "Total Customers",
        "Average Order Value",
        "Purchase Frequency",
        "Customer Lifetime Value"
    ],
    "Value": [
        total_revenue,
        total_orders,
        total_customers,
        aov,
        purchase_frequency,
        cltv
    ]
})

metrics_summary

                    Metric         Value
0            Total Revenue  1.897249e+07
1             Total Orders  5.296100e+04
2          Total Customers  5.924000e+03
3      Average Order Value  3.582352e+02
4       Purchase Frequency  8.940074e+00
5  Customer Lifetime Value  3.843179e+04

In [6]:
pd.options.display.float_format = '{:.2f}'.format

metrics_summary

                    Metric       Value
0            Total Revenue 18972492.19
1             Total Orders    52961.00
2          Total Customers     5924.00
3      Average Order Value      358.24
4       Purchase Frequency        8.94
5  Customer Lifetime Value    38431.79

In [7]:
metrics_summary.to_csv(
    "metrics_summary.csv",
    index=False
)

In [8]:
from google.colab import files

files.download("metrics_summary.csv")