In [1]:
import pandas as pd
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving online_retail_II.xlsx to online_retail_II.xlsx

In [2]:
df_2009 = pd.read_excel("online_retail_II.xlsx", sheet_name="Year 2009-2010")
df_2010 = pd.read_excel("online_retail_II.xlsx", sheet_name="Year 2010-2011")

df = pd.concat([df_2009, df_2010], ignore_index=True)

In [3]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [9]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

In [6]:
df["InvoiceDate"].dtype

dtype('<M8[ns]')

In [7]:
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["Day"] = df["InvoiceDate"].dt.day
df["Day_Name"] = df["InvoiceDate"].dt.day_name()

In [10]:
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Year,Month,Day,Day_Name
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,2009,12,1,Tuesday
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,1,Tuesday
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,2009,12,1,Tuesday
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,2009,12,1,Tuesday
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,2009,12,1,Tuesday

In [11]:
df["InvoiceDate"].isnull().sum()

np.int64(0)

In [12]:
df["Year"].value_counts()
df["Month"].value_counts().sort_index()

Month
1      66702
2      57095
3      78259
4      63973
5      72353
6      76857
7      72901
8      68590
9      92317
10    119840
11    162726
12    135758
Name: count, dtype: int64

In [14]:
df.to_csv("processed_online_retail.csv", index=False)

In [15]:
import os

os.listdir()

['.config',
 'processed_online_retail.csv',
 'online_retail_II.xlsx',
 'sample_data']

In [16]:
from google.colab import files

files.download("processed_online_retail.csv")