In [9]:
import pandas as pd
import numpy as np

In [1]:
from google.colab import files

uploaded = files.upload()

Saving cohort_dataset.csv to cohort_dataset.csv

In [10]:
df = pd.read_csv("cohort_dataset.csv")

In [11]:
df.shape

(1048575, 15)

In [12]:
df.isnull().sum()

Invoice                     0
StockCode                   0
Description              4372
Quantity                    0
InvoiceDate                 0
Price                       0
Customer ID            236682
Country                     0
Year                        0
Month                       0
Day                         0
Day_Name                    0
First_Purchase_Date    236682
Cohort_Month                0
Order_Month                 0
dtype: int64

In [13]:
df["Customer ID"].nunique()

5924

In [14]:
df["Invoice"].nunique()

52961

In [15]:
print("Start Date:", df["InvoiceDate"].min())
print("End Date:", df["InvoiceDate"].max())

Start Date: 2009-12-01 07:45:00
End Date: 2011-12-04 13:15:00

In [19]:
df["Revenue"] = df["Quantity"] * df["Price"]

In [20]:
df["Revenue"].describe()

count    1.048575e+06
mean     1.809360e+01
std      1.798897e+02
min     -7.718360e+04
25%      3.750000e+00
50%      9.900000e+00
75%      1.770000e+01
max      7.718360e+04
Name: Revenue, dtype: float64

In [18]:
df["Cohort_Month"].value_counts().sort_index()

Cohort_Month
2009-12    340585
2010-01     64546
2010-02     53278
2010-03     60903
2010-04     28338
2010-05     23081
2010-06     27402
2010-07     20990
2010-08     17479
2010-09     20935
2010-10     33275
2010-11     26235
2010-12      4858
2011-01      6112
2011-02      7295
2011-03     12450
2011-04      6954
2011-05      5881
2011-06      6589
2011-07      7333
2011-08      9541
2011-09      9748
2011-10     11346
2011-11      6585
2011-12       154
NaT        236682
Name: count, dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 16 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   Invoice              1048575 non-null  object
 1   StockCode            1048575 non-null  object
 2   Description          1044203 non-null  object
 3   Quantity             1048575 non-null  int64
 4   InvoiceDate          1048575 non-null  object
 5   Price                1048575 non-null  float64
 6   Customer ID          811893 non-null   float64
 7   Country              1048575 non-null  object
 8   Year                 1048575 non-null  int64
 9   Month                1048575 non-null  int64
 10  Day                  1048575 non-null  int64
 11  Day_Name             1048575 non-null  object
 12  First_Purchase_Date  811893 non-null   object
 13  Cohort_Month         1048575 non-null  object
 14  Order_Month          1048575 non-null  object
 15  Revenue              1048575 non-null  float64
dtypes: float64(3), int64(4), object(9)
memory usage: 128.0+ MB